### ISSUE TITLE
Two typos in the text

### ISSUE THREAD

**Issue by ariasdereyna** [DarkerStar/epub-turing-computing-machinery-and-intelligence#1]
I have detected two typos

(A) In the file: section-5.xhtml,  line 25  we read (position of ]ever) instead of (position of lever).

(B) In the file section-5.xhtml,  line 22  we read "but may be stopped by a ]ever which can be..." instead of but may be stopped by a lever which can be...

(C) There is another one:

Section 6, line 323  there is a "h" that should be "such".

**Comment by DarkerStar** [comment]
Thank you for the heads up! I’ll get the ball rolling on a fix right away!
